language: ruby
cache:
  bundler: true
  directories:
    - ${HOME}/duckdb-v0.1.2
    - ${HOME}/duckdb-v0.1.3
before_install:
  - yes | gem update --system
  - if [[ ! -d ${HOME}/duckdb-v0.1.2/build ]]; then cd ${HOME} && git clone -b v0.1.2 https://github.com/cwida/duckdb.git duckdb-v0.1.2 && cd duckdb-v0.1.2 && make && cd ${TRAVIS_BUILD_DIR}; fi
  - if [[ ! -d ${HOME}/duckdb-v0.1.3/build ]]; then cd ${HOME} && git clone -b v0.1.3 https://github.com/cwida/duckdb.git duckdb-v0.1.3 && cd duckdb-v0.1.3 && make && cd ${TRAVIS_BUILD_DIR}; fi

env:
  - DUCKDB_VERSION=0.1.2
  - DUCKDB_VERSION=0.1.3
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
script: bundle exec rake -- --with-duckdb-include=${HOME}/duckdb-v${DUCKDB_VERSION}/src/include --with-duckdb-lib=${HOME}/duckdb-v${DUCKDB_VERSION}/build/release/src/
