language: ruby
cache:
  bundler: true
  directories:
    - ${HOME}/duckdb-v0.2.9
before_install:
  - yes | gem update --system
  - if [[ ! -d ${HOME}/duckdb-v0.2.9/build ]]; then cd ${HOME} && git clone -b v0.2.9 https://github.com/cwida/duckdb.git duckdb-v0.2.9 && cd duckdb-v0.2.9 && make && cd ${TRAVIS_BUILD_DIR}; fi

env:
  - DUCKDB_VERSION=0.2.9
rvm:
  - 2.6.8
  - 2.7.4
  - 3.0.2
  - ruby-head
script: bundle exec rake -- --with-duckdb-include=${HOME}/duckdb-v${DUCKDB_VERSION}/src/include --with-duckdb-lib=${HOME}/duckdb-v${DUCKDB_VERSION}/build/release/src/
