name: Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5.8', '2.6.7', '2.7.3', '3.0.1', 'head']
        duckdb: ['0.2.6', '0.2.5']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: duckdb 0.2.6 cache
      id: duckdb-cache-v0_2_6
      uses: actions/cache@v1.1.0
      with:
        path: duckdb-v0.2.6
        key: ${{ runner.os }}-duckdb-v0_2_6_001
        restore-keys: |
          ${{ runner.os }}-duckdb-v0_2_6

    - name: duckdb 0.2.5 cache
      id: duckdb-cache-v0_2_5
      uses: actions/cache@v1.1.0
      with:
        path: duckdb-v0.2.5
        key: ${{ runner.os }}-duckdb-v0_2_5_001
        restore-keys: |
          ${{ runner.os }}-duckdb-v0_2_5

    - name: Build duckdb 0.2.6
      if: steps.duckdb-cache-v0_2_6.outputs.cache-hit != 'true'
      run: |
        git clone -b v0.2.6 https://github.com/cwida/duckdb.git duckdb-tmp-v0.2.6
        cd duckdb-tmp-v0.2.6 && make && cd ..
        rm -rf duckdb-v0.2.6
        mkdir -p duckdb-v0.2.6/build/release/src duckdb-v0.2.6/src
        cp -rip duckdb-tmp-v0.2.6/build/release/src/*.so duckdb-v0.2.6/build/release/src
        cp -rip duckdb-tmp-v0.2.6/src/include duckdb-v0.2.6/src/

    - name: Build duckdb 0.2.5
      if: steps.duckdb-cache-v0_2_5.outputs.cache-hit != 'true'
      run: |
        git clone -b v0.2.5 https://github.com/cwida/duckdb.git duckdb-tmp-v0.2.5
        cd duckdb-tmp-v0.2.5 && make && cd ..
        rm -rf duckdb-v0.2.5
        mkdir -p duckdb-v0.2.5/build/release/src duckdb-v0.2.5/src
        cp -rip duckdb-tmp-v0.2.5/build/release/src/*.so duckdb-v0.2.5/build/release/src
        cp -rip duckdb-tmp-v0.2.5/src/include duckdb-v0.2.5/src/

    - name: Build and test with Rake with Ruby ${{ matrix.ruby }}
      env:
        DUCKDB_VERSION: ${{ matrix.duckdb }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake -- --with-duckdb-include=${GITHUB_WORKSPACE}/duckdb-v${DUCKDB_VERSION}/src/include --with-duckdb-lib=${GITHUB_WORKSPACE}/duckdb-v${DUCKDB_VERSION}/build/release/src/
