name: MacOS

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        ruby: ['2.5.8', '2.6.7', '2.7.3', '3.0.1', 'head']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install latest duckdb by brew
      run: |
        brew install duckdb

    - name: Build and test with Rake with Ruby ${{ matrix.ruby }}
      run: |
        ruby -v
        bundle install --jobs 4 --retry 3
        bundle exec rake
